### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by gamesbook** [iiSeymour/chromote#14]
Is the full documentation available anywhere for the API?

I am looking for a way to open multiple tabs and cycle between them, preferably without reloading the tab each time.

**Comment by iiSeymour** [comment]
The API documentation is here https://chromedevtools.github.io/devtools-protocol/1-2/

**Comment by gamesbook** [comment]
But if I search that for 'tab' or 'tabs' nothing shows up; does chromote itself have any further docs?

**Comment by iiSeymour** [comment]
Chromote is a very simple [wrapper](https://github.com/iiSeymour/chromote/blob/master/chromote/__init__.py#L25) around the API and you can see examples in the [README.md](https://github.com/iiSeymour/chromote/blob/master/README.md).

It is not possible to cycle tabs with the Chrome API but you could use a local caching proxy to load each site from.
