### ISSUE TITLE
Using chromote for multiple Chrome processes with different debugger ports?

### ISSUE THREAD

**Issue by Decker108** [iiSeymour/chromote#6]
Is it possible to use Chromote for multiple Chrome processes with different debugger ports? For example, if I open two new Chrome windows with debugger port 9222 and port 9223, can I create two Chromote instances in a single parent process and connect them to their respective browser processes?

The reason for this is that I want to use Chromote as a load testing tool for a web application, where a number of clients open up browsers and remote control them simultaneously.

**Comment by iiSeymour** [comment]
Yes, there is no problem with instantiating multiple `Chromote` objects to connect to difference browsers.
