### ISSUE TITLE
How do we get the contents of the page from the tab?

### ISSUE THREAD

**Issue by vgoklani** [iiSeymour/chromote#7]
from chromote import Chromote
	chrome = Chromote()

	chrome.tabs[0].set_url('http://www.nytimes.com')
        print(chrome.tabs[0])

"The New York Times - Breaking News, World News &amp; Multimedia - https://www.nytimes.com/"

How we we get the contents of the page?

**Comment by iiSeymour** [comment]
What are you trying to do? Do you want the DOM or HTML source?

**Comment by beautron7** [comment]
I am having a similar problem, is there any way to get the (current) html source of the page?

**Comment by iiSeymour** [comment]
I've added the `html` property to the `ChromeTab` object and pushed 0.2.0 to pypi.

```
from chromote import Chromote
chrome = Chromote()
print chrome.tabs[0]
print chrome.tabs[0].html
```
